base_url = "https://yechenz37.tech"
title = "Chen's Blog"
# description = "A (nearly) no-CSS, fast, minimalist Zola theme."

theme = "no-style-please"

compile_sass = true
generate_feeds = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]

[markdown]
highlight_code = true

[extra]
author = "Chen Ye"
logo = "images/logo.png"
header_nav = [
    { name = "~home", url = "/" },
    { name = "#tags", url = "/tags" },
    { name = "+categories", url = "/categories" },
#    { name = "@contexts", url = "/contexts" },
]
footer_nav = [
#     { name = "< previous", url = "#" },
#     { name = "webring", url = "#" },
#     { name = "next >", url = "#" },
]

list_pages = true