name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: 0.19.2
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Zola
      run: |
        curl -sL https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin
    - name: Install static-sitemap-cli
      run: |
        npm install static-sitemap-cli
    - name: Build
      run: |
        git submodule update --init --recursive
        zola build
    - name: Deploy GitHub Pages
      run: |
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../public/* .
        # Copy root *.html to .
        cp ../*.html .
        # Copy CNAME to .
        cp ../CNAME .
        # Generate sitemap.xml
        npx sscli --no-clean --base https://yechenz37.tech
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
